version: "3"

services:

  nginx:
    image: nginx:1.15-alpine
    container_name: nginx-container
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/nginx/web:/var/log/nginx/web
    command:
      "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - backbone

  green:
    build: .
    container_name: green
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./:/home/ubuntu
      - /etc/localtime:/etc/localtime
    networks:
      - backbone

  blue:
    build: .
    container_name: blue
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./:/home/ubuntu
      - /etc/localtime:/etc/localtime
    networks:
      - backbone

networks:
  backbone:
    driver: bridge