version: "3"

services:

  database:
    container_name: mysql
    image: mysql/mysql-server:latest
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: test1234
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: rootpwd
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - 3305:3306
    networks:
      - db_network
    restart: always

  web-server:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/

  green:
    build: .
    container_name: myweb-green
    restart: always
    expose:
      - 8080
    depends_on:
      - database
    volumes:
      - ./:/home/ubuntu
      - /etc/localtime:/etc/localtime

  blue:
    build: .
    container_name: myweb-blue
    restart: always
    expose:
      - 8080
    depends_on:
      - database
    volumes:
      - ./:/home/ubuntu
      - /etc/localtime:/etc/localtime

networks:
  db_network:
    driver: bridge