version: "3"
services:
  database:
    container_name: mysql
    image: mysql/mysql-server:latest
    environment:
      MYSQL_DATABASE: goorm
      MYSQL_USER: admin
      MYSQL_PASSWORD: jejugoorm
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: rootpwd
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    networks:
      - db_network
    restart: always
  mytamla:
    build: .
    container_name: mytamla-green
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - database

networks:
  db_network:
    driver: bridge
